version: "3.7"
services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        networks:
          - app-tier
        environment: 
            ALLOW_ANONYMOUS_LOGIN: "yes"

    kafka:
        image: bitnami/kafka
        ports:
            - '9092:9092'
            - '29092:29092'
        environment: 
            ALLOW_PLAINTEXT_LISTENER: "yes"
            KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"            
        networks:
            - app-tier

    app:
        image: golang
        command: "go run /go-game-kafka/cmd/client.go"
        volumes:
            - ./:/go-game-kafka
        networks:
            - app-tier
networks:
    app-tier:
        driver: bridge
              